### ISSUE TITLE
Crash with quilt

### ISSUE THREAD

**Issue by Stick404** [miyucomics/hexcellular#2]
Hexcellular crashes on quilt due to not recognizing the Quilt Kotlin Libraries. The log for this crash can be found here https://mclo.gs/P4GQIVf and the pack is the same one for the HexxyCraft++ server (or the one in #another-minecraft-server)

**Comment by miyucomics** [comment]
Does Hexical have the same crash? They both rely on the same version of Kotlin so I would be concerned if it didn't. Do you have [Fabric Language Kotlin](https://modrinth.com/mod/fabric-language-kotlin) installed? Hexcellular was made for Fabric and I assumed it would work for Quilt since I heard Fabric mods were automatically compatible.

**Comment by miyucomics** [comment]
Okay, I looked into it and it seems Quilt's Kotlin thing comes with Fabric Language Kotlin 1.9.0 and I'm relying on a later version. Luckily, this is a quick fix! Not only that, it forewarned me about an issue with the current dev version of Hexical!

**Comment by miyucomics** [comment]
Hexcellular 1.0.1 is out now and it should be fixed!
